import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/SideBar';
import { ThemeProvider } from '@/components/ThemeProvider'
import MobileNav from '@/components/MobileNav'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className="bg-white dark:bg-slate-950 transition-colors duration-300">
        <ThemeProvider>
          {/* Menu Lateral e Botão Mobile */}
          <MobileNav>
            <Sidebar />
          </MobileNav>

          {/* Wrapper do Conteúdo */}
          <div className="md:pl-64 min-h-screen flex flex-col">
            <div className="flex-1 w-full max-w-7xl mx-auto p-4 md:p-8 lg:p-12">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}